[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd packages/api && npx tsc"]

[start]
cmd = "cd packages/api && node dist/index.js"
